import { useEffect, useRef, useState } from 'react';
import { X, Send, Sparkles } from 'lucide-react';
import { motion, AnimatePresence } from 'framer-motion';
import { useTranslation } from 'react-i18next';
import '../ai-chat.css';

type Language = 'en' | 'ru' | 'hy';
type Message = { role: 'user' | 'ai'; text: string };
const contact = '\n\n📞 +374 41 083882\n📩 isalationit@gmail.com';
const content = {
 en: { online:'Online now', placeholder:'Describe your business challenge…', quick:['Business problem','AI system','Custom software','Timeline','Budget'], welcome:'👋 I’m Isolation AI. I help turn complex ideas into clear software projects.\n\nWhat does your company do, what problem should the product solve, and who will use it?', greeting:'Hello 👋 Tell me about the business problem you want to solve. I’ll help identify the product direction and next step.', budget:'We estimate serious software projects after a short discovery because architecture, integrations and data affect scope. Our inquiry ranges are $5k–$10k, $10k–$25k, $25k–$50k and $50k+. What are you building?', timeline:'A reliable timeline depends on scope, integrations and release strategy. What is your target launch date, which features are essential, and must we connect an existing system?', ai:'We build applied AI systems: assistants, intelligent workflows, data analysis, recommendations and operational automation. Which decision or repetitive process should AI improve?', software:'We engineer custom software, web/SaaS platforms, mobile products, admin systems and integrations. Who will use the product, and which workflow must change?', fallback:'This sounds like a potential software project. Tell me three things: the business goal, the main users and the most important workflow. I’ll help structure the product and next step.' },
 ru: { online:'Сейчас онлайн', placeholder:'Опишите бизнес-задачу…', quick:['Бизнес-задача','AI-система','Заказное ПО','Сроки','Бюджет'], welcome:'👋 Я Isolation AI. Помогаю превращать сложные идеи в понятные software-проекты.\n\nЧем занимается компания, какую проблему должен решить продукт и кто будет им пользоваться?', greeting:'Здравствуйте 👋 Расскажите о бизнес-задаче. Я помогу определить направление продукта и следующий шаг.', budget:'Серьёзные software-проекты мы оцениваем после короткого discovery: на scope влияют архитектура, интеграции и данные. Диапазоны заявки: $5k–$10k, $10k–$25k, $25k–$50k и $50k+. Что вы создаёте?', timeline:'Реальный срок зависит от scope, интеграций и стратегии релиза. Какая желаемая дата запуска, обязательные функции и существующие системы?', ai:'Мы создаём прикладные AI-системы: ассистентов, интеллектуальные workflow, анализ данных, рекомендации и автоматизацию. Какое решение или повторяющийся процесс должен улучшить AI?', software:'Мы разрабатываем заказное ПО, web/SaaS-платформы, mobile-продукты, админ-системы и интеграции. Кто будет пользоваться продуктом и какой workflow должен измениться?', fallback:'Это может стать сильным software-проектом. Уточните цель бизнеса, основных пользователей и самый важный workflow — я помогу структурировать продукт и следующий шаг.' },
 hy: { online:'Առցանց է', placeholder:'Նկարագրեք բիզնես խնդիրը…', quick:['Բիզնես խնդիր','AI համակարգ','Custom Software','Ժամկետ','Բյուջե'], welcome:'👋 Ես Isolation AI-ն եմ։ Օգնում եմ բարդ գաղափարները դարձնել հստակ software նախագծեր։\n\nԻնչո՞վ է զբաղվում ընկերությունը, ի՞նչ խնդիր պետք է լուծի պրոդուկտը և ո՞վ է այն օգտագործելու։', greeting:'Բարև 👋 Պատմեք բիզնես խնդրի մասին։ Կօգնեմ որոշել պրոդուկտի ուղղությունը և հաջորդ քայլը։', budget:'Լուրջ software նախագծերը գնահատում ենք կարճ discovery-ից հետո․ scope-ի վրա ազդում են architecture-ը, integrations-ը և տվյալները։ Միջակայքներն են $5k–$10k, $10k–$25k, $25k–$50k և $50k+։ Ի՞նչ եք ստեղծում։', timeline:'Իրատեսական ժամկետը կախված է scope-ից, integrations-ից և release strategy-ից։ Ո՞րն է ցանկալի launch date-ը, պարտադիր ֆունկցիաները և առկա համակարգերը։', ai:'Մենք ստեղծում ենք կիրառական AI համակարգեր՝ assistants, intelligent workflow-ներ, տվյալների վերլուծություն և ավտոմատացում։ Ո՞ր որոշումը կամ կրկնվող գործընթացը պետք է բարելավի AI-ը։', software:'Մենք մշակում ենք custom software, web/SaaS հարթակներ, mobile պրոդուկտներ, admin համակարգեր և integrations։ Ո՞վ է օգտագործելու պրոդուկտը և ո՞ր workflow-ն է փոխվելու։', fallback:'Սա կարող է դառնալ ուժեղ software նախագիծ։ Նշեք բիզնես նպատակը, հիմնական օգտատերերին և կարևոր workflow-ն․ կօգնեմ կառուցել պրոդուկտը և հաջորդ քայլը։' }
};

export default function AIChatWidget(){
 const {i18n}=useTranslation(); const code=i18n.resolvedLanguage?.split('-')[0] as Language; const c=content[code]??content.en;
 const [open,setOpen]=useState(false),[input,setInput]=useState(''),[typing,setTyping]=useState(false); const [messages,setMessages]=useState<Message[]>([]); const end=useRef<HTMLDivElement|null>(null);
 useEffect(()=>{const fn=()=>setOpen(true);window.addEventListener('open-isolation-ai',fn);return()=>window.removeEventListener('open-isolation-ai',fn)},[]);
 useEffect(()=>{end.current?.scrollIntoView({behavior:'smooth'})},[messages,typing]);
 const answer=(message:string)=>{const t=message.toLowerCase();if(/^(hi|hello|hey|привет|здравствуйте|բարև|բարեւ)/i.test(t))return c.greeting+contact;if(/price|cost|budget|цена|стоим|бюджет|գին|արժեք|բյուջե/i.test(t))return c.budget+contact;if(/time|timeline|launch|срок|запуск|ժամկետ|գործարկ/i.test(t))return c.timeline+contact;if(/ai|assistant|ии|нейро|արհեստական|օգնական/i.test(t))return c.ai+contact;if(/software|platform|saas|mobile|crm|admin|integration|система|платформ|прилож|автомат|համակարգ|հարթակ|ավտոմատ/i.test(t))return c.software+contact;return c.fallback+contact};
 const type=(text:string)=>{setTyping(true);let i=0,current='';setMessages(v=>[...v,{role:'ai',text:''}]);const timer=window.setInterval(()=>{current+=text[i]??'';setMessages(v=>{const n=[...v];n[n.length-1]={role:'ai',text:current};return n});i++;if(i>=text.length){clearInterval(timer);setTyping(false)}},8)};
 const send=(quick?:string)=>{const value=quick||input;if(!value.trim()||typing)return;setMessages(v=>[...(v.length?v:[{role:'ai' as const,text:c.welcome+contact}]),{role:'user',text:value}]);setInput('');setTimeout(()=>type(answer(value)),260)};
 return <><motion.button className="aiButton" whileTap={{scale:.9}} whileHover={{scale:1.08}} onClick={()=>setOpen(true)} aria-label="Open Isolation AI"><Sparkles size={28}/></motion.button><AnimatePresence>{open&&<motion.div className="aiChat" initial={{opacity:0,y:40,scale:.9}} animate={{opacity:1,y:0,scale:1}} exit={{opacity:0,y:20,scale:.92}}><div className="aiHeader"><div><strong>Isolation AI</strong><span>{c.online}</span></div><button className="aiClose" onClick={()=>setOpen(false)} aria-label="Close"><X size={18}/></button></div><div className="aiQuick">{c.quick.map(q=><button key={q} onClick={()=>send(q)} disabled={typing}>{q}</button>)}</div><div className="aiMessages">{(messages.length?messages:[{role:'ai' as const,text:c.welcome+contact}]).map((m,i)=><div key={i} className={`aiMsg ${m.role}`}><div style={{whiteSpace:'pre-line'}}>{m.text}</div></div>)}{typing&&<div className="aiThinking"><span/><span/><span/></div>}<div ref={end}/></div><div className="aiInput"><input value={input} onChange={e=>setInput(e.target.value)} placeholder={c.placeholder} onKeyDown={e=>{if(e.key==='Enter')send()}}/><button onClick={()=>send()} disabled={typing} aria-label="Send"><Send size={18}/></button></div></motion.div>}</AnimatePresence></>
}
